#!/usr/bin/env python3
import json
import os

MIDDLE_DOT = '\u00b7'

def normalize_title(title: str) -> str:
    return title.replace(MIDDLE_DOT, '').replace(' ', '')

def make_canonical_key(title: str, author: str) -> str:
    return f"{normalize_title(title)}:{author}"

def main():
    print("Loading data/meilisearch_poems.json...")
    with open("data/meilisearch_poems.json", "r", encoding="utf-8") as f:
        poems = [json.loads(line) for line in f]
    
    print(f"Loaded {len(poems)} records.")

    canonical_groups = {}
    for p in poems:
        title = p.get('title', '')
        author = p.get('author', '')
        dynasty = p.get('dynasty', '')
        lines = p.get('lines', [])
        content = [l.strip() for l in lines if l and l.strip()]
        
        canonical = make_canonical_key(title, author)
        if canonical not in canonical_groups:
            canonical_groups[canonical] = []
        canonical_groups[canonical].append((title, author, content, len(content), dynasty))

    merged = []
    for canonical, entries in canonical_groups.items():
        entries.sort(key=lambda e: e[3], reverse=True)
        title, author, content, _, dynasty = entries[0]
        
        merged.append({
            "t": title.strip(),
            "a": author.strip(),
            "d": dynasty,
            "content": content,
        })

    out_json = "public/data/all_poems_lookup.json"
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump({"poems": merged}, f, ensure_ascii=False)
    size_mb = os.path.getsize(out_json) / 1024 / 1024
    print(f"\nWritten {out_json} ({size_mb:.1f} MB)")

    ts_out = "src/data/allPoemsLookup.ts"
    with open(ts_out, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/build_all_poems.py — DO NOT EDIT\n")
        f.write('"use client";\n\n')
        f.write("/** 全部诗词本地查找 */\n")
        f.write("export interface PoemData { t: string; a: string; d: string; content: string[]; }\n\n")
        f.write("let _cache: Map<string, PoemData> | null = null;\n\n")
        f.write("const MIDDLE_DOT = '\\u00b7'\n")
        f.write("function normalizeTitle(title: string): string {\n")
        f.write("  return title.replace(MIDDLE_DOT, '').replace(/ /g, '')\n")
        f.write("}\n\n")
        f.write("async function _load(): Promise<Map<string, PoemData>> {\n")
        f.write("  if (_cache) return _cache;\n")
        f.write("  const res = await fetch('/data/all_poems_lookup.json');\n")
        f.write("  const data: { poems: PoemData[] } = await res.json();\n")
        f.write("  _cache = new Map();\n")
        f.write("  for (const p of data.poems) {\n")
        f.write("    const canonical = `${normalizeTitle(p.t)}:${p.a}`\n")
        f.write("    _cache.set(canonical, p)\n")
        f.write("  }\n")
        f.write("  return _cache;\n")
        f.write("}\n\n")
        f.write("export function getPoemByKeyFast(key: string): PoemData | undefined {\n")
        f.write("  if (!_cache) return undefined\n")
        f.write("  const lastColon = key.lastIndexOf(':')\n")
        f.write("  if (lastColon < 0) return undefined\n")
        f.write("  const title = key.slice(0, lastColon)\n")
        f.write("  const author = key.slice(lastColon + 1)\n")
        f.write("  return _cache.get(`${normalizeTitle(title)}:${author}`)\n")
        f.write("}\n\n")
        f.write("export async function loadAllPoemsLookup(): Promise<Map<string, PoemData>> {\n")
        f.write("  return _load();\n")
        f.write("}\n")
    print(f"Written {ts_out}")
    print("\nDone!")

if __name__ == "__main__":
    main()
