// AUTO-GENERATED by scripts/build_all_poems.py — DO NOT EDIT
"use client";

/** 全部诗词本地查找 */
export interface PoemData { t: string; a: string; d: string; content: string[]; }

let _cache: Map<string, PoemData> | null = null;

const MIDDLE_DOT = '\u00b7'
function normalizeTitle(title: string): string {
  return title.replace(MIDDLE_DOT, '').replace(/ /g, '')
}

async function _load(): Promise<Map<string, PoemData>> {
  if (_cache) return _cache;
  _cache = new Map();
  return _cache;
}

export function getPoemByKeyFast(key: string): PoemData | undefined {
  if (!_cache) return undefined
  const lastColon = key.lastIndexOf(':')
  if (lastColon < 0) return undefined
  const title = key.slice(0, lastColon)
  const author = key.slice(lastColon + 1)
  return _cache.get(`${normalizeTitle(title)}:${author}`)
}

export async function loadAllPoemsLookup(): Promise<Map<string, PoemData>> {
  return _load();
}
