// AUTO-GENERATED by scripts/build_all_poems.py — DO NOT EDIT
"use client";

/** 全部诗词本地查找（content 来自 poems_content.json，干净无 markup）。
 *  total=192266 | titleVariantsDeduped=248 | missingDyn=0
 */

export interface PoemData { t: string; a: string; d: string; content: string[]; }

let _cache: Map<string, PoemData> | null = null;

// 规范化标题：去掉 · 和空格，确保变体标题查到同一首诗
const MIDDLE_DOT = '\u00b7'
function normalizeTitle(title: string): string {
  return title.replace(MIDDLE_DOT, '').replace(/ /g, '')
}

async function _load(): Promise<Map<string, PoemData>> {
  if (_cache) return _cache;
  const res = await fetch('/data/all_poems_lookup.json');
  const data: { poems: PoemData[] } = await res.json();
  _cache = new Map();
  for (const p of data.poems) {
    const canonical = `${normalizeTitle(p.t)}:${p.a}`
    _cache.set(canonical, p)
  }
  return _cache;
}

export function getPoemByKeyFast(key: string): PoemData | undefined {
  if (!_cache) return undefined
  const lastColon = key.lastIndexOf(':')
  if (lastColon < 0) return undefined
  const title = key.slice(0, lastColon)
  const author = key.slice(lastColon + 1)
  return _cache.get(`${normalizeTitle(title)}:${author}`)
}

export async function loadAllPoemsLookup(): Promise<Map<string, PoemData>> {
  return _load();
}
